name: Continous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  continous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Using Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.
      - name: Install Build and Test dependencies
        run: |
          npm install
          npm run build
          npm run cypress:headless
          

        
